[package]
name = "core-momentum"
version = "0.1.0"
authors = ["James Lemieux <jrlmx2@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "*"
rustc-serialize = "*"
meval = "*"
regex = "*"
chrono = "*"

[dependencies.postgres]
features = ["with-serde_json-1"]
version = "0.16.0-rc.2"
