[package]
name = "rust-portfolio"
version = "0.1.0"
authors = ["James Lemieux <jrlmx2@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
