[package]
name = "rust-portfolio"
version = "0.1.0"
authors = ["James Lemieux <jrlmx2@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.11.14"
postgres = "0.16.0-rc.2"

[workspace]
members = [
    "indicators",
    "database"
]

